// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smkhryfgldkzcihaadeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNta2hyeWZnbGRremNpaGFhZGVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NTcxMjksImV4cCI6MjA3MzMzMzEyOX0.yQfMwceXelFSUtSl8KosJnj0M-8fo-QoYDLbep7x7yM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});